"""Models package for supervised and probabilistic baselines."""

from .match_prediction import (
    DixonColesModel,
    EnsemblePrediction,
    IndependentPoissonModel,
    MatchMomentum,
    MatchProbabilitySummary,
    MomentumPoint,
    PoissonPrediction,
    PredictionConfidenceInterval,
    bootstrap_prediction_confidence,
    compute_form_weights,
    compute_momentum,
    ensemble_prediction,
    fit_dixon_coles,
    fit_dixon_coles_with_form,
    fit_independent_poisson,
    optimize_ensemble_weights,
    predict_match,
    predict_match_dc,
    update_probability_at_scoreline,
)
from .player_rating_nn import (
    PlayerRatingNNConfig,
    PlayerRatingNNResult,
    train_player_rating_nn,
    train_player_rating_nn_from_files,
)
from .value_fairness import (
    TimeSplitConfig,
    ValueFairnessResult,
    classify_fairness,
    fit_regressor,
)

__all__ = [
    "DixonColesModel",
    "EnsemblePrediction",
    "IndependentPoissonModel",
    "MatchMomentum",
    "MatchProbabilitySummary",
    "MomentumPoint",
    "PlayerRatingNNConfig",
    "PlayerRatingNNResult",
    "PoissonPrediction",
    "PredictionConfidenceInterval",
    "TimeSplitConfig",
    "ValueFairnessResult",
    "bootstrap_prediction_confidence",
    "classify_fairness",
    "compute_form_weights",
    "compute_momentum",
    "ensemble_prediction",
    "fit_dixon_coles",
    "fit_dixon_coles_with_form",
    "fit_independent_poisson",
    "fit_regressor",
    "optimize_ensemble_weights",
    "predict_match",
    "predict_match_dc",
    "train_player_rating_nn",
    "train_player_rating_nn_from_files",
    "update_probability_at_scoreline",
]
